/**
 * 경일 학업설계 플랫폼 — 과목 설명 이미지 공통 맵 (v3.2)
 * 원천: subjects/index.html 의 PDF_IMGS (서울시교육청 교육과정 안내서)
 * 소비: choice(과목명 옆 ? 아이콘). 하위 앱(../) 기준 상대경로.
 * 갱신법: subjects 이미지 교체 시 이 파일의 경로만 함께 갱신하면 된다.
 */
(function () {
  'use strict';
  var MAP = {
"화법과 언어": "../subjects/assets/subj/s001.webp",
"독서와 작문": "../subjects/assets/subj/s002.webp",
"문학": "../subjects/assets/subj/s003.webp",
"주제 탐구 독서": "../subjects/assets/subj/s004.webp",
"문학과 영상": "../subjects/assets/subj/s005.webp",
"직무 의사소통": "../subjects/assets/subj/s006.webp",
"독서 토론과 글쓰기": "../subjects/assets/subj/s007.webp",
"매체 의사소통": "../subjects/assets/subj/s008.webp",
"언어생활 탐구": "../subjects/assets/subj/s009.webp",
"대수": "../subjects/assets/subj/s010.webp",
"미적분Ⅰ": "../subjects/assets/subj/s011.webp",
"확률과 통계": "../subjects/assets/subj/s012.webp",
"기하": "../subjects/assets/subj/s013.webp",
"미적분Ⅱ": "../subjects/assets/subj/s014.webp",
"경제 수학": "../subjects/assets/subj/s015.webp",
"인공지능 수학": "../subjects/assets/subj/s016.webp",
"직무 수학": "../subjects/assets/subj/s017.webp",
"수학과 문화": "../subjects/assets/subj/s018.webp",
"실용 통계": "../subjects/assets/subj/s019.webp",
"수학과제 탐구": "../subjects/assets/subj/s020.webp",
"영어Ⅰ": "../subjects/assets/subj/s021.webp",
"영어Ⅱ": "../subjects/assets/subj/s022.webp",
"영어 독해와 작문": "../subjects/assets/subj/s023.webp",
"영미 문학 읽기": "../subjects/assets/subj/s024.webp",
"영어 발표와 토론": "../subjects/assets/subj/s025.webp",
"심화 영어": "../subjects/assets/subj/s026.webp",
"심화 영어 독해와 작문": "../subjects/assets/subj/s027.webp",
"직무 영어": "../subjects/assets/subj/s028.webp",
"실생활 영어 회화": "../subjects/assets/subj/s029.webp",
"미디어 영어": "../subjects/assets/subj/s030.webp",
"세계 문화와 영어": "../subjects/assets/subj/s031.webp",
"세계시민과 지리": "../subjects/assets/subj/s032.webp",
"세계사": "../subjects/assets/subj/s033.webp",
"사회와 문화": "../subjects/assets/subj/s034.webp",
"현대사회와 윤리": "../subjects/assets/subj/s035.webp",
"한국지리 탐구": "../subjects/assets/subj/s036.webp",
"도시의 미래 탐구": "../subjects/assets/subj/s037.webp",
"동아시아 역사 기행": "../subjects/assets/subj/s038.webp",
"정치": "../subjects/assets/subj/s039.webp",
"법과 사회": "../subjects/assets/subj/s040.webp",
"경제": "../subjects/assets/subj/s041.webp",
"윤리와 사상": "../subjects/assets/subj/s042.webp",
"인문학과 윤리": "../subjects/assets/subj/s043.webp",
"국제 관계의 이해": "../subjects/assets/subj/s044.webp",
"여행지리": "../subjects/assets/subj/s045.webp",
"역사로 탐구하는 현대 세계": "../subjects/assets/subj/s046.webp",
"사회문제 탐구": "../subjects/assets/subj/s047.webp",
"금융과 경제생활": "../subjects/assets/subj/s048.webp",
"윤리문제 탐구": "../subjects/assets/subj/s049.webp",
"기후변화와 지속가능한 세계": "../subjects/assets/subj/s050.webp",
"물리학": "../subjects/assets/subj/s051.webp",
"화학": "../subjects/assets/subj/s052.webp",
"생명과학": "../subjects/assets/subj/s053.webp",
"지구과학": "../subjects/assets/subj/s054.webp",
"역학과 에너지": "../subjects/assets/subj/s055.webp",
"전자기와 양자": "../subjects/assets/subj/s056.webp",
"물질과 에너지": "../subjects/assets/subj/s057.webp",
"화학 반응의 세계": "../subjects/assets/subj/s058.webp",
"세포와 물질대사": "../subjects/assets/subj/s059.webp",
"생물의 유전": "../subjects/assets/subj/s060.webp",
"지구시스템과학": "../subjects/assets/subj/s061.webp",
"행성우주과학": "../subjects/assets/subj/s062.webp",
"과학의 역사와 문화": "../subjects/assets/subj/s063.webp",
"기후변화와 환경생태": "../subjects/assets/subj/s064.webp",
"융합과학 탐구": "../subjects/assets/subj/s065.webp",
"체육1": "../subjects/assets/subj/s066.webp",
"체육2": "../subjects/assets/subj/s067.webp",
"운동과 건강": "../subjects/assets/subj/s068.webp",
"스포츠 문화": "../subjects/assets/subj/s069.webp",
"스포츠 과학": "../subjects/assets/subj/s070.webp",
"스포츠 생활1": "../subjects/assets/subj/s071.webp",
"스포츠 생활2": "../subjects/assets/subj/s072.webp",
"음악": "../subjects/assets/subj/s073.webp",
"음악 연주와 창작": "../subjects/assets/subj/s074.webp",
"음악 감상과 비평": "../subjects/assets/subj/s075.webp",
"음악과 미디어": "../subjects/assets/subj/s076.webp",
"미술": "../subjects/assets/subj/s077.webp",
"미술 창작": "../subjects/assets/subj/s078.webp",
"미술 감상과 비평": "../subjects/assets/subj/s079.webp",
"미술과 매체": "../subjects/assets/subj/s080.webp",
"연극": "../subjects/assets/subj/s081.webp",
"기술·가정": "../subjects/assets/subj/s082.webp",
"로봇과 공학세계": "../subjects/assets/subj/s083.webp",
"생활과학 탐구": "../subjects/assets/subj/s084.webp",
"창의 공학 설계": "../subjects/assets/subj/s085.webp",
"지식 재산 일반": "../subjects/assets/subj/s086.webp",
"생애 설계와 자립": "../subjects/assets/subj/s087.webp",
"아동발달과 부모": "../subjects/assets/subj/s088.webp",
"정보": "../subjects/assets/subj/s089.webp",
"인공지능 기초": "../subjects/assets/subj/s090.webp",
"데이터 과학": "../subjects/assets/subj/s091.webp",
"소프트웨어와 생활": "../subjects/assets/subj/s092.webp",
"제2외국어": "../subjects/assets/subj/s093.webp",
"심화 제2외국어": "../subjects/assets/subj/s094.webp",
"제2외국어 회화": "../subjects/assets/subj/s095.webp",
"제2외국어권 문화": "../subjects/assets/subj/s096.webp",
"한문": "../subjects/assets/subj/s097.webp",
"한문 고전 읽기": "../subjects/assets/subj/s098.webp",
"언어생활과 한자": "../subjects/assets/subj/s099.webp",
"진로와 직업": "../subjects/assets/subj/s100.webp",
"생태와 환경": "../subjects/assets/subj/s101.webp",
"인간과 철학": "../subjects/assets/subj/s102.webp",
"논리와 사고": "../subjects/assets/subj/s103.webp",
"인간과 심리": "../subjects/assets/subj/s104.webp",
"교육의 이해": "../subjects/assets/subj/s105.webp",
"삶과 종교": "../subjects/assets/subj/s106.webp",
"보건": "../subjects/assets/subj/s107.webp",
"인간과 경제활동": "../subjects/assets/subj/s108.webp",
"논술": "../subjects/assets/subj/s109.webp",
"미적분 Ⅰ": "../subjects/assets/subj/s110.webp",
"미적분I": "../subjects/assets/subj/s111.webp",
"미적분1": "../subjects/assets/subj/s112.webp",
"미적분 Ⅱ": "../subjects/assets/subj/s113.webp",
"미적분II": "../subjects/assets/subj/s114.webp",
"미적분2": "../subjects/assets/subj/s115.webp",
"영어 Ⅰ": "../subjects/assets/subj/s116.webp",
"영어I": "../subjects/assets/subj/s117.webp",
"영어1": "../subjects/assets/subj/s118.webp",
"영어 Ⅱ": "../subjects/assets/subj/s119.webp",
"영어II": "../subjects/assets/subj/s120.webp",
"영어2": "../subjects/assets/subj/s121.webp",
"역사로 탐구하는 현대세계": "../subjects/assets/subj/s122.webp",
"기후변화와 지속가능한세계": "../subjects/assets/subj/s123.webp"
};
  var L2 = /독일어|프랑스어|스페인어|중국어|일본어|러시아어|아랍어|베트남어/;
  window.GyeongilSubjectImages = {
    /** 과목명 → 이미지 경로 (없으면 null). 공백 차이·제2외국어 공통 이미지 처리 */
    find: function (name) {
      if (!name) return null;
      var n = String(name).trim();
      return MAP[n] || MAP[n.replace(/\s+/g, '')] ||
        (L2.test(n) ? MAP['제2외국어'] : null) || null;
    }
  };
})();
